### ISSUE TITLE
 ERROR #11321  PLUGIN Must supply cloud_name

### ISSUE THREAD

**Issue by indefinit** [Chuloo/gatsby-source-cloudinary#28]
I keep getting this error when I run gatsby build. I've added my cloudName and credentials per the installation instructions and using dotenv. Any ideas how to get rid of the error message?

ERROR #11321  PLUGIN

"gatsby-source-cloudinary" threw an error while running the sourceNodes lifecycle:

Must supply cloud_name

**Comment by Chuloo** [comment]
could you check if it's a valid cloud name? You can just use a sample Cloudinary image URL on your browser. Also, print the .env data in development anywhere to see if the value is passed. Let me know if all these are positive while I try to reproduce it.

**Comment by indefinit** [comment]
I think I figured out where the problem is. It seems to be related to the gatsby-config.js. In the plugin documentation it recommends placing the cloudinary api config in a .env.development file, and then in gatsby-config.js:

```
// Load the environment variables.
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`,
});
```

but if I run the gatsby build command the node env is no longer looking for development. Renaming .env.development to .env, and removing the NODE_ENV specificity prevents the error during gatsby build:
```
require('dotenv').config({
  path: `.env`,
});
``` 
But I'm not sure if this is an ideal solution, if a user wants to specify different .env variables at build and develop stages. Is there a better way to solve for this?

**Comment by Chuloo** [comment]
Yes, that's the solution. Typically you may want to maintain different .env definitions for your environments. If it's the same .env config across dev and production then you can just use `.env` instead of `.env.development` or `.env.production`. 

You can add a `.env.development` file too with the dev variables if you like.

Also, to specify different ENV then you can add the NODE_ENV config in your scripts object in package.json. Something like

`"build": "NODE_ENV=production gatsby build"` 

Replace the NODE_ENV value for the dev command.

**Comment by indefinit** [comment]
Ah ok great thanks for the suggestion!
